name: Use My Python Action

on:
  push:
    branches: main 

jobs:
  run-my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom Python action
        uses: ./my-python-action
        with:
          name: "Cyber Warrior Jiyadh"
